### ISSUE TITLE
Video transcoding with multiple qualities [AMP Stories]

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/transcoder#119]
Add multiple quality videos in transcoding. 
Like this - 

- High Quality - CRF value 18
- Medium Quality - CRF value 23
- Low Quality - CRF value 28

In AMP Story Gutenberg Block -

Add options as shown in the image below. 

![thumbnail](https://user-images.githubusercontent.com/1139853/67941053-e2fae500-fbfa-11e9-933d-fe01a90d0dfc.jpg)

**Comment by pradeep910** [comment]
@dharmin 

- [ ] Add option to enable / disable multiple video quality selection in the transcoder plugin itself. The options will show up only if its enable.
- [ ]  Meta will have 3 different URLs for low, mid and high quality. 

Store meta like this
`array[0] == low quality video`
`array[1] == mid quality video`
`array[2] == high quality video`

```
| 305     | _rt_media_transcoded_files | a:1:{s:3:"mp4";a:1:{i:0;s:46:"2019/10/1572519757-vid-20190930-114423-4-3.mp4";}}        |
```

**Comment by pooja-muchandikar** [comment]
@thrijith 

I have tested and below are some of my findings.

- [ ] 1. In the first page if video is uploaded from media library video which was already present, the transcoder settings flicker. This issue also occurs when media is uploaded from local system and happens only with mp4 file format 
https://drive.google.com/file/d/15C8juFlnKYVnGfHRnlN3tlm9hhfmrIMQ/view

- [ ] 2. webm file format URL is not changing. The video is getting transcoded and playing but when checked for the quality status found that the URL didn't get changed
https://drive.google.com/file/d/1bW-7fk8vq6WOyaAOtUXyc1PcEdC7k6vh/view

- [ ] 3. Uploaded video preview is not visible. 

- [ ] 4. Video uploaded from local system takes more time to transcode, in frontend the video looks transcoded but in the stories page video poster default image is shown

for 3rd and 4th refer this visual -> https://drive.google.com/file/d/1cCVOB1Umh1qHDgJcdbto6ogXqip4dcUF/view

- [ ] 5. 3gp video format is allowed as per ReadMe but when uploaded video with 3gp format it not allowing to upload, error is shown
![image](https://user-images.githubusercontent.com/41000648/71717805-40035900-2e3f-11ea-8726-ec1979ef73bf.png)

- [ ] 6. flv video format video failed to play
![image](https://user-images.githubusercontent.com/41000648/71717973-d0419e00-2e3f-11ea-801e-8acdd1ad36d9.png)

- [ ] 7. An error message is shown in the block when mp4 file format is uploaded from local system. First the uploaded media is not visible, check uploading the same media in another block and observe that after updating `block encountered error cannot be previewed` error is shown
https://drive.google.com/file/d/1n52TL6xbfxsCm9EmMx2KJqr_m3fJRfAw/view

- [ ] 8. The background quality settings should be shown after clicking on the video in the block or on clicking on the block? Because currently the settings are shown only shown on clicking on the video in the block.

The background quality settings are working fine as per the settings set. And also are shown in the URL.

cc: @pradeep910

**Comment by pradeep910** [comment]
This is not relevant in Gutenberg block of AMP plugin now. But we can think of this for Transcoder with Webstories as per of  https://github.com/rtCamp/labs/issues/66
