### ISSUE TITLE
Page reload after the media's are transcoded

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/transcoder#182]
When a media is uploaded after the media gets transcoded, user needs to explicitly reload the page. Where as page should reload once the media gets transcoded. 

Need to find a way to fix this issue.

**Comment by SID177** [comment]
Instead of page reload, we will just update the thumbnail.

When a video gets transcoded, a thumbnail of that video is generated and its displayed instead of a default video icon.
https://drive.google.com/file/d/15zMM0vgODsbHk93ov02PUAGgGP0YCVp-/view?usp=sharing
In the above visual, notice that the thumbnail is displayed only after page reload. We need to check if it can be done without page reload, that the thumbnail gets updated after video is transcoded.

**Comment by pooja-muchandikar** [comment]
@SID177 

I checked this issue with `develop` branch and this is not working as expected.

**Comment by pooja-muchandikar** [comment]
@SID177 

Cross-checked the issue with `develop` branch and the media thumbnails are shown after the media is transcoded and without explicitly reloading the page :heavy_check_mark:

**Comment by pooja-muchandikar** [comment]
This is released in `v1.3.1`
